### ISSUE TITLE
2.4.5 Die Rolls - downgrade result due to successful augment?

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#124]
Augments can turn a big success into a success. 

Example: 13 is your ability rating and +5 is your augment, i.e. the TN is 18. You roll a 13. It means you only have a success, whereas you would have had a big success without the augment. 

Mathematically that is OK, because the augment kept the chance for big success untouched and increased the chance for success. Nevertheless, it feels awkward and my players were sometimes disappointed by it. I think there is no need to change the system, but a short explanation for players might be helpful.  

BTW I just realised that fumbles no longer exist. I can't track the history for that. Can anybody give me the reasons for the removal?

**Comment by jrutila** [comment]
The big success moving away is great fuel for your narration. Why did the augment actually prevent the big success in the end?

If i recall correctly the fumbles went away the same time the big success on exact TN and counting successes was introduced. I think the negative successes and the edge cases with TN 20 are complicating the play too much.

**Comment by Robin-Mitra** [comment]
Thank you. 
When the TN is 18 (13+5) and players roll a 13 they only have a regular success. Without the augment it would have been a big success. Although this is correct, it is hard for me to explain to my players how a successful augment caused a smaller result. Player A complains to Player B: "If you had not helped me, I would have succeeded better." Player B to Player A: "How can that be true? My help was successful?"

**Comment by jrutila** [comment]
This goes little bit into the same idea that is in the rules about PC succeeding but still getting a defeat:

> Your GM should avoid robbing your PC of competence by describing your defeat as due to your incompetence when you may have rolled a success.

So, in the same lieu the player B successfully augmented but still caused only normal success. This might happen other ways, too. If Player A rolled a 16 they would get one success and The GM gets a big succeess. Player A lost even if they both (B and A) succeeded in their rolls.

Let me try an example:
Abe and Bill get into a gun fight against the syndicate mook. The goal is to get not harmed. Secondary goal is to get the mook captured alive. Bill is not a gunslinger so this is a contest between Abe and the mook. Abe uses their gunslinger ability 13. Bill augments with tactician ability and succeeds giving the +5. During the fight Bill finds a better vantage point to see the mook better dodging the mooks attempt to prevent him. GM rolls one success (4) and Abe rolls 13, one success, also. The result is a zero level victory (high roll wins) for Abe. The player chooses the "no harm" goal.
During the fight Abe is pushing the mook from the right side of the ship container. All of sudden the mook decides to advance from left. Bill shouts to Abe just in time to warn him. The mook hears this also and advances. Abe has no choice but to make a clear shot to the chest. The mook is dead.
"Thanks Bill, but leave the gun fights to me. I knew what he was going to do but your shout alerted him, also. Well, dead mook is the best mook, as they say."

So, the augment succeeded (Bill got into the vantage point) and caused, in narration, only a zero degree victory instead of one level victory.
I don't know if this example helps and, of course, the goals and tactics and intents are not always in favor of twisting the narration to address the lost big success. But it is a nice exercise of improvised narration, at least.

**Comment by iancooper** [comment]
But the player will now get a Big Success on an 18. So it's important to recognize that your TN is what matters not your rating. I'm not sure it is part of the SRD, but I'll consider a box out in the Core Rules.
