### ISSUE TITLE
[Enhancement] Edges and Handicaps advice

### ISSUE THREAD

**Issue by davecake** [ChaosiumInc/QuestWorlds#17]
5.3.13 contains some advice about inadvisable use of Edges and Handicaps, but very little about appropriate use of these mechanics. It is also confusing in its discussion of defensive vs offensive use. 

The example of weapons and armour confuses the issue, as it misrepresents the Hero Wars rules (in which armour and weapon ranks were compared to generate a resultant edge or handicap), resulting in the confusing implication that superiour armour or other purely defensive abilities is best treated as an Edge, rather than effectively a Handicap to the opponent. I'd advise keeping the idea that certain opponents present a Handicap to certain opponents, rather than having Edges or Handicaps apply only to the defender in a contest, and perhaps introduce additional terminology (defensive edge or defensive handicap?).

More importantly, I'd introduce language about the appropriate use of Edges and Handicaps. Something like:
Edges and Handicap should generally not be used as a general mechanism to track detailed differences in equipment throughout a game (they are only relevant in Extended Contests, so do a poor job, and tracking possessions in this manner is seldom a core part of the narrative), but used sparingly as a mechanism to customise specific contests or specific opponents when it is relevant to the narrative. Opponents with Edges can maintain a sense of tension even when their Target Number is relatively low, or defensive Edges can make it clear that while opponents are not difficult to defeat for your PCs they represent a danger to others. They can make a fight with a giant that is clumsy but wields and an enormous club, or a zombie that is slow but incredibly difficult to destroy, distinct and memorable. Social interaction with aliens might still be relatively easy to gain a Victory if the Prize is a modest request, but the risk of giving offence might still be large. They can be used to emphasize large disparities in equipment level where it is an element of a specific contest (your characters are caught while bathing or otherwise unprepared), or if the difference is a campaign theme (your characters are prisoners, or the technological advantage of a colonial power is a significant theme). If using Edges and Handicaps in this manner, you may allow them to be changed by Unrelated Actions, Benefits or Consequences, or by longer term achievement of campaign goals. 
In a more complex situation, such as a Group Extended Contest, you may use Edges and Handicaps to offer a tactical choice, for example where one way of achieving a goal of defeating an opponent is easier but more time consuming or arduous.

**Comment by jlaufersweiler** [comment]
[Link to §5.3.13 in master, for reference.](https://github.com/ChaosiumInc/QuestWorlds/blob/master/5.3_Extended_Contest.md#5313-edges-and-handicaps)

**Comment by jlaufersweiler** [comment]
E & H seem to me like a tool for injecting credibility-based factors into a contest in a game where abilities & resistance are being rated according to story-oomph. If a monster is more/less vulnerable to fire, for example, the AP result of an exchange might be raised or lowered to reflect that. As a credability-based tool, it might be good to also include guidance similar (or refer back) to [§2.1.1.2 Making Abilities Quantitative](https://github.com/ChaosiumInc/QuestWorlds/blob/master/2.1_Abilities.md#2112-making-ratings-quantitative)

Ideally, guidance in their use should include when to use them rather than situational Augments, Stretches or simply raising or lowering Resistance values - all of which cover similar ground. One PC in a group contest wielding a fire against a paper golum might be a sensible use case, the Resistance is the same for everyone, but that character's results might be more impactful towards the outcome, without having higher odds of a successful result on any given exchange as one would with an Augment.

E&H, Risky Gambit/Defensive Responses, Phyrric Victory, and Costly/Arduous auto-victory all sort of dance around a gap in general contest framing around setting stakes. Explicitly coupling states of adversity to contest outcomes makes it hard to handle things like the Resistance to attaining your goal being only moderate, but the stakes might be such that you could be looking at being Hurt (or equivalent) even on a Major Victory. We might do well to open another issue to look at Costly/Arduous principles being somehow applicable outside of automatic Victory - Phyrric sort of does that now.

**Comment by iancooper** [comment]
Thanks @jlaufersweiler let me ponder some wording for a PR

**Comment by davecake** [comment]
_E & H seem to me like a tool for injecting credibility-based factors into a contest in a game where abilities & resistance are being rated according to story-oomph._ 

 Yes, and as such has a few different ways it can be used, but some of them (like later HW turning it into a generic mechanism for injecting simulationist elements) are unhelpful. It is helpful for when you want to highlight those aspects for story reasons, without significantly changing the chance of success. It's also notable that the rules are only there for Extended Contests - and they suggest to me that the reasons for a detailed long contests should not always simply come down to contests with significant chances of failure, but can be about demonstrating important aspects of setting or character, etc. Eg a vulnerability or strength of certain opponents is first discovered or demonstrated in an Extended Contest, which may then be taken as a pure change to difficulty numbers from then on, as its understood and accounted for.

**Comment by iancooper** [comment]
PS this current draft was based on something RL wrote for HQ 2 but was not published when HQ2 dropped extended contests for Scored. That intent is important

**Comment by iancooper** [comment]
I'll pick this up next

**Comment by iancooper** [comment]
I've tweaked the wording here, closing the issue
