### ISSUE TITLE
Confusing use of "Quantitative"

### ISSUE THREAD

**Issue by Tanaka84** [ChaosiumInc/QuestWorlds#21]
On the header 2.1.1.2 Making Ratings Quantitative, the explanation does not infer that ability ratings are being used as a quantitative measure. In the example given, the ratings are taken as a threshold for assigning an ordinal category (such as proficiency level).

For something to be considered quantitative in the formal sense, you would need to have some sort of mathematical relation such as "If your rating doubles your opponents you don't need to roll for a conflict" or "Your rating divided by 5 is x"

 As such, I would recommend changing the name to "Using ratings as Thresholds".

**Comment by jlaufersweiler** [comment]
Those would also be good examples. I've played around with using divisors with ratings to come up with D&D-style spells per day too. The resistance benchmarks in the HQ1 are another approach.

The SRD is thin on examples though, by its nature. I went with the threshold example because it's a simple one and loosely mirrors the rune initiate/devotee mechanic in HQ. It's not meant to be the sole application of the principle.

**Comment by iancooper** [comment]
@Tanaka84 Good suggestion, thanks.

**Comment by Tanaka84** [comment]
No prob, also @jlaufersweiler I wholeheartedly agree that the example used in the text is the least cumbersome, it's easier to grasp and is more flavorful than my dull examples :) I guess that being a methodoly professor has made a terrible nitpicker.

**Comment by iancooper** [comment]
Raised PR #40
