### ISSUE TITLE
Masteries can also give bump downs

### ISSUE THREAD

**Issue by SergiDiaz** [ChaosiumInc/QuestWorlds#29]
While there's some reference to it (2.3.5.4 Bumps has this sentence: "Bump downs come from one source: masteries."), there isn't any clear indication that leftover masteries after reaching a critical results in bump downs to the opponent result. 2.3.5.4 Bump Up with Mastery only mentions bump ups. There should be an extra sentence there after the second paragraph similar to this one: "If you still have some masteries advantage over your opponent when reaching a critical result, each of those masteries give a bump down to the opponent result".

**Comment by iancooper** [comment]
Thanks

**Comment by jlaufersweiler** [comment]
Come to think of it, are we sure bumping down with a Hero Point is not legitimate if you're already at a critical? I'm imagining PC rolling a natural crit result and resistance rolling a fail. In such a circumstance the Player might reasonably want to spend a Hero Point to bump the resistance down to fumble in order to get a Complete Victory rather than Major Victory outcome.

I could also see spending an HP on the uncommon-but-does-happen case of critical vs critical Marginal or Tie outcome to bump resistance down to regular success and net the PC a Minor Victory outcome.

Is there any reason these shouldn't be allowed?

**Comment by iancooper** [comment]
hi @jlaufersweiler, I'm going to raise a fix for the issue, and then we can discuss this further as an enhancement

**Comment by iancooper** [comment]
Raised #42

**Comment by iancooper** [comment]
On the issue of changing the prohibition on hero points to bump down.

I suspect this is historic. In Hero Wars or Heroquest v1 pools of hero points were not uncommon, and could be unbalancing if used this way. Now hero points are a more scarce resource, so it might make sense to allow it.

I'd be clear you could only bump down with hero points, once you were at critical.

Thoughts?

**Comment by Robin-Mitra** [comment]
In my opinion it will rarely enhance game play, because players will mostly refrain from using HP if they already have a success. However, it could be entertaining to spend HP in a critical vs. major outcome (to get a permanent achievement on a complete victory) or even in a critical vs. critical. 

Also it would make the rules slightly easier, what is always good. So I opt for allowing it.

**Comment by iancooper** [comment]
Raised #55
