### ISSUE TITLE
[fix] Mastery-rated Resistance can also bump.

### ISSUE THREAD

**Issue by jlaufersweiler** [ChaosiumInc/QuestWorlds#51]
In looking over the bump sections (2.3.5.3 - 2.3.5.6), it now occurs to me that in our focus on Player-addressing language, we left unstated the case of Restistance with a mastery advantage bumping its result up or a PC's result down. This seems remiss.

The bump sections also do not address the case of a negative Mastery  from Rock Bottom level Resistance (or even Tiny if the base were <10 for some reason).

**Comment by iancooper** [comment]
I agree that we should ensure that the resistance bumping down as well is explicitly mentioned.

On the negative mastery, we should address that if the resistance falls below 0.

I would assume that we agree that it is an auto-success (in the same way that if a player's ability falls below 0 due to modifiers they automatically are defeated)?

**Comment by jlaufersweiler** [comment]
On the rare occasions when it has come up, I've still rolled 14M-1 as TN14 with a bump-down (or whatever base), making (as I use crit-on-rating) 1-13 failures, 14 a success, and 15-20 fumbles. If I'm bothering to call for a roll at all vs Rock Bottom resistance, it's usually some sort of costly/ardruous situation, so rolling produces a useful/interesting range of outcomes when combined with the PC's result.

I agree though that if degree of victory is not relevant, skipping the roll at that point makes sense.

**Comment by iancooper** [comment]
Raised #60
