### ISSUE TITLE
[Enhancement] Make Pendragon results the default

### ISSUE THREAD

**Issue by iancooper** [ChaosiumInc/QuestWorlds#53]
For anyone coming from Pendragon, the QuestWorlds default of critical 1, fumble 20 is confusing when we couple with better roll is higher roll. For Pendragon players TN is critical, 1 is fumble, and higher roll is better makes much more sense.

Overall I think that the Pendragon model works better. High roll better is more intuitive. And if you have a higher roll better, TN for critical makes more sense.

So I am thinking of making this the default with Questworlds and then documenting the other approaches (critical on 1 fumble on 20, better roll wins, where better is low or high as an optional).

I think this has become a direction of travel ever since we admitted to 'high roll wins' as more intuitive

Comments?

**Comment by jlaufersweiler** [comment]
I am 100% in favor of making crit-on-rating the default. Not only is it more in tune with high-roll winning ties, it also enables rolled crits to edge out mastery-bumped crits at times, which makes for dramatic reversals.

However, I believe you're mis-remembering how Pendragon handles fumbles, or perhaps remembering an early edition. In KAP 5.1 at least, 20 is a fumble (unless your skill is 20+), and that's how I've been doing it in HQ for years as well. 

Making 1 into fumble has an unintended consequence of shifting the odds of every roll towards failure. Shrinking the number of successful roll possibilities and increasing the number of unsuccessful possibilities by 1 each drops any rating's chance of a successful or better result by 5%. Resistance would be affected as well, so there's still some parity there, but the distribution of outcomes would shift slightly across the board. I think that's an undesirable side effect. Further, it's much more intuitive for a 15 rating to mean a 75% chance of a successful result, rather than 70%.

If not making 1 a Fumble, the question then arises of how to handle a rolled 20 when the rating hits 20. KAP still makes it a critical. When I'm running, I make 20 a regular fail. Essentially rolling your rating bumps the fumble up one result-grade just like it bumps success up to crit otherwise. 

I sometimes go a step further and let a 20 rating still crit on a rolled 19. It's not quite as clean, but keeps both crits and a small chance of failure in the result set. While I like that result set (18 successes, 1 crit, and 1 fail is a nice transitional state before you hit Mastery) , it's perhaps a bit awkward for a default approach.

Whether 20-rating is handled KAP's style or mine though, I definitely think Pendragon-style is best.

**Comment by Robin-Mitra** [comment]
My approach is this: All rules should be as easy and intuitive as possible. The current system works, but usually needs a few minutes of explaining to new players. Therefore I would welcome a change in how to roll dice. 

    1. In a higher roll wins system it makes sense that the TN is the best result. I agree here. 

    2. However I would not make 1 a fumble, because it is in the range of the “good numbers”. If 1 would be fumble and TN would be crit, it would be bad->good->good->bad (i.e. 1->belowTN->TN->aboveTN). 

    3. Making 20 a fumble would be an improvement to this system, because then all numbers up to TN are good, and all above TN are bad. 

    4. Then again comes the reminder that high roll wins, so why would the 20 be worse than the 19? To stick to the high roll wins system the lowest failure should be the fumble and 20 should be the best failure. That would make TN+1 a fumble. In this case higher successes are better then lower successes and higher failures are still better than lower failures. Easy. I know this would be a major change, but the more I think about it, the more I like it.

**Comment by iancooper** [comment]
@Robin-Mitra I understand the desire for TN +1, but I worry how easy it is to 'spot' in play.

@jlaufersweiler I had missed the issue with reducing the success percentage. It also adds the slight problem that when your ability is a 20, you can succeed, critical or fumble, but not fail.

For now, I am going to mirror Pendragon explicity. @Robin-Mitra if you want to playtest your variation and let us know how it went, then the feedback would be useful. We can reconsider if it seems to be more seamless than we might expect.

**Comment by iancooper** [comment]
Raised #63

**Comment by Robin-Mitra** [comment]
> For now, I am going to mirror Pendragon explicity. @Robin-Mitra if you want to playtest your variation and let us know how it went, then the feedback would be useful. We can reconsider if it seems to be more seamless than we might expect.

Ok, I will run a Redcow session again next week and will report after that.

**Comment by dscarpenter** [comment]
Here's my utterly non-mathematical take on the question:

If the rules position higher rolls as better, then most folk will see the lowest possible roll (1) as the worst possible result. 

A "nat 1" is already the worst possible roll in many other games, including the most popular competitive title from which many new players would be migrating. 

If I were in the designer's chair, I'd gladly sacrifice a 5% variation in outcomes for clarity. The gut-turning reaction to seeing that 1 pop-up on your die is worth it, in my opinion.

**Comment by iancooper** [comment]
Thanks @dscarpenter. It's useful feedback. Let's contemplate for a bit, it's small enough to change. For now, I'll close this issue, we can raise a new one when we have had a chance to playtest options
