### ISSUE TITLE
[Enhancement] Simplification – Experience Points list

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#61]
[Should Simplifications be suggested under #54 or separately?]

One list I would like to simplify is the XP expenditure in 7.1. 
I cannot memorise it and it seems unnecessarily complex.  Why not simply say: “For 10 XP you can raise abilities by 10 points, keywords by 5 points and introduce a new ability at 13”. 

Another way could be to use a more flexible “end of season” instead of the rather rigid 10 XP requirement, e.g.: “At the end of the story arc you will get 2 ability points and 1 keyword point for every 2 XP you have. You will also get one new ability for free.”

Or something along those lines. 

I also opened a separate issue on HP-XP conversion #62

**Comment by iancooper** [comment]
I can see your point about ease. It is one to add to the list. We took the mechanic of thresholds from Prince Valiant really.

**Comment by iancooper** [comment]
My intent is to get to this, after we work through the remove tables issue (particularly the removal of degrees of victory and defeat).

This is partially due to the fact that I believe removing degrees of victory and defeat removes one key use case for hero points: improving the degree of victory or lessening the consequences of defeat.

That may create options around hero points i.e. you just get one per session, that allow us to separate them from experience points without imposing the bookkeeping cost of tracking two counters.

**Comment by iancooper** [comment]
One thing I am looking at is linking experience points to defined traits, inspired a bit by The Shadows of Yesterday (once described as love letter to Hero Wars). They might work particularly well in a Gloranthan product where your runes would substitute for keys. That implies keys would be specific to a setting

**Comment by iancooper** [comment]
Going to drop for the new thread on experience
