### ISSUE TITLE
Gain XP on defeat not failure

### ISSUE THREAD

**Issue by iancooper** [ChaosiumInc/QuestWorlds#71]
So over on the FB forum Ashley Munday pointed out that there is an anomaly with the XP on failure as written. A single digit mastery, say 1W, will gain more XP against a single mastery resistance, say 13W, than a double digit ability would, say 17.

Now, I suspect the number of times this anomaly occurs in play is not enough for it to be unbalancing, but it does stick out a little.

So the suggestion was just to award XP on defeat. It mostly has the same effect - persuade the players not to always buy off a defeat but let the story branch - and it will also tend to mean that groups who consistently out-perform the resistance will tend to slow down from defeats.

I don't like the principle as much, but I can't remove the anomaly. And whilst I don't think it effects play, I do think it will cause friction for folks that notice it.

**Comment by jrutila** [comment]
I was thinking about this briefly when you introduced the xp-on-failure but didn't go deeply into it. It seemed elegant to get XP on failure instead of getting it on just defeat. It is also in-line with the increased focus on roll results (instead of the contest outcome). Maybe the xp-on-defeat would suffice.

Something, on top of my head, that I came up to combat against the anomaly is that the player gets XP if they roll failure (even if bumped to failure) **and** the player roll is below the resistance target number. That way 3W vs 3W does not really generate XP but 3W vs 17W does. That way 17 vs 14 wouldn't generate XP, either. Don't know if that is a good or a bad thing...

**Comment by iancooper** [comment]
I appreciate the sentiment, I did too.

The trouble with that approach is it feels fiddly and we want quick. I can't see an quick way to remove the mastery anomaly that doesn't involve players doing complicated review of the dice at the table. I thought about making it, you fail and get a worse result, but that is just defeat :-)  I did think about failure and defeat i.e. you both fail your roll and lose, and you don't get XP if you succeed and lose. But I am not sure I gain a lot from that extra step.

**Comment by jrutila** [comment]
One more idea I got during biking would be that the xp-on-failure only works on abilities without masteries. After the character gets a mastery that ability can generate XP only on defeat. I don't know if this really helps or just makes things more complicated.

**Comment by iancooper** [comment]
@jrutila oh it definitely helps to throw ideas out. I thought about that, but I guess the question becomes does that make game play better for the cost of introducing two cases. Is the advantage of failure over defeat great enough to feel that. And my assumption is no, a simple system that is slightly less resonant is better than a more complex one

**Comment by iancooper** [comment]
Created #72 for this
